version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:14.15.3

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package.json" }}

  save_npm:
    steps:
      - save_cache:
          name: Save npm dependencies
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/workspace/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_npm

  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  
  deploy:
    executor:
      name: default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "61:bb:bf:ef:4c:a5:e6:80:58:f9:77:ad:f2:b5:73:d6"
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            cd dist
            echo 'konnyaku256.dev' > CNAME
            git config --global user.name "Circle CI"
            git config --global user.email "<>"
            git init
            git add -A
            git commit -m "Deploy by CI"
            git push -f git@github.com:konnyaku256/konnyaku256.github.io.git master

workflows:
  deploy:
    jobs:
      - setup:
          filters:
            branches:
              only: master
      - build:
          requires:
            - setup
      - deploy:
          requires:
            - build